version: "3.8"

services:
  db:
    image: postgres:16
    container_name: trip_db
    environment:
      POSTGRES_DB: tripdb
      POSTGRES_USER: tripuser
      POSTGRES_PASSWORD: trippass
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tripuser -d tripdb"]
      interval: 5s
      timeout: 3s
      retries: 30

  app:
    image: tm04/tripbudgeter:1.1
    container_name: trip_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tripdb
      SPRING_DATASOURCE_USERNAME: tripuser
      SPRING_DATASOURCE_PASSWORD: trippass
    restart: on-failure

volumes:
  postgresdata: