spring.application.name=TripBudgeter
spring.datasource.url=jdbc:postgresql://localhost:5432/tripdb
spring.datasource.username=tripuser
spring.datasource.password=trippass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect